In [1]:
import torch

/home/mohammed/environments/pytorch/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
tensor = torch.rand((2,2,31))
tensor

tensor([[[0.9486, 0.0850, 0.1063, 0.0067, 0.2461, 0.9002, 0.4634, 0.6427,
          0.3104, 0.8627, 0.6274, 0.0134, 0.4124, 0.1732, 0.5279, 0.3208,
          0.9502, 0.8870, 0.1719, 0.6970, 0.2901, 0.9707, 0.1482, 0.5649,
          0.2174, 0.4802, 0.4095, 0.8936, 0.0412, 0.3774, 0.7505],
         [0.5434, 0.7439, 0.3548, 0.8869, 0.3824, 0.8402, 0.7259, 0.1865,
          0.3054, 0.2553, 0.8669, 0.5740, 0.2662, 0.4297, 0.9937, 0.5173,
          0.8148, 0.3263, 0.6613, 0.6234, 0.1905, 0.1564, 0.5201, 0.6037,
          0.6186, 0.4140, 0.2468, 0.5946, 0.8167, 0.5324, 0.6688]],

        [[0.8356, 0.5837, 0.9390, 0.8477, 0.6490, 0.3628, 0.5433, 0.5418,
          0.2012, 0.7774, 0.8451, 0.7966, 0.8403, 0.9259, 0.2477, 0.4336,
          0.2979, 0.7580, 0.7799, 0.7837, 0.8351, 0.3850, 0.8184, 0.7992,
          0.4769, 0.2866, 0.2027, 0.2437, 0.8937, 0.5089, 0.3297],
         [0.5591, 0.1938, 0.8390, 0.4451, 0.6021, 0.1795, 0.9531, 0.9111,
          0.3802, 0.5065, 0.8737, 0.3987, 0.8884, 0.7352,

In [3]:
tensor.size()

torch.Size([2, 2, 31])

In [4]:
tensor1 = torch.zeros(3,4)
tensor1

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [5]:
ones = torch.ones(3,2,1)
ones

tensor([[[1.],
         [1.]],

        [[1.],
         [1.]],

        [[1.],
         [1.]]])

In [6]:
ones*2

tensor([[[2.],
         [2.]],

        [[2.],
         [2.]],

        [[2.],
         [2.]]])

In [7]:
ranged = torch.range(3,8,.06)
ranged

/tmp/ipykernel_2502/1058934983.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  ranged = torch.range(3,8,.06)


tensor([3.0000, 3.0600, 3.1200, 3.1800, 3.2400, 3.3000, 3.3600, 3.4200, 3.4800,
        3.5400, 3.6000, 3.6600, 3.7200, 3.7800, 3.8400, 3.9000, 3.9600, 4.0200,
        4.0800, 4.1400, 4.2000, 4.2600, 4.3200, 4.3800, 4.4400, 4.5000, 4.5600,
        4.6200, 4.6800, 4.7400, 4.8000, 4.8600, 4.9200, 4.9800, 5.0400, 5.1000,
        5.1600, 5.2200, 5.2800, 5.3400, 5.4000, 5.4600, 5.5200, 5.5800, 5.6400,
        5.7000, 5.7600, 5.8200, 5.8800, 5.9400, 6.0000, 6.0600, 6.1200, 6.1800,
        6.2400, 6.3000, 6.3600, 6.4200, 6.4800, 6.5400, 6.6000, 6.6600, 6.7200,
        6.7800, 6.8400, 6.9000, 6.9600, 7.0200, 7.0800, 7.1400, 7.2000, 7.2600,
        7.3200, 7.3800, 7.4400, 7.5000, 7.5600, 7.6200, 7.6800, 7.7400, 7.8000,
        7.8600, 7.9200, 7.9800])

In [8]:
ranged = torch.arange(3,8,.06)
ranged

tensor([3.0000, 3.0600, 3.1200, 3.1800, 3.2400, 3.3000, 3.3600, 3.4200, 3.4800,
        3.5400, 3.6000, 3.6600, 3.7200, 3.7800, 3.8400, 3.9000, 3.9600, 4.0200,
        4.0800, 4.1400, 4.2000, 4.2600, 4.3200, 4.3800, 4.4400, 4.5000, 4.5600,
        4.6200, 4.6800, 4.7400, 4.8000, 4.8600, 4.9200, 4.9800, 5.0400, 5.1000,
        5.1600, 5.2200, 5.2800, 5.3400, 5.4000, 5.4600, 5.5200, 5.5800, 5.6400,
        5.7000, 5.7600, 5.8200, 5.8800, 5.9400, 6.0000, 6.0600, 6.1200, 6.1800,
        6.2400, 6.3000, 6.3600, 6.4200, 6.4800, 6.5400, 6.6000, 6.6600, 6.7200,
        6.7800, 6.8400, 6.9000, 6.9600, 7.0200, 7.0800, 7.1400, 7.2000, 7.2600,
        7.3200, 7.3800, 7.4400, 7.5000, 7.5600, 7.6200, 7.6800, 7.7400, 7.8000,
        7.8600, 7.9200, 7.9800])

In [9]:
ranged_like = torch.zeros_like(ranged)
ranged_like

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
ranged.size()

torch.Size([84])

In [11]:
%time
torch.matmul(ranged, ranged)

CPU times: user 2 µs, sys: 1 µs, total: 3 µs
Wall time: 5.01 µs


tensor(2709.5544)

In [12]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

In [13]:
torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [14]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [15]:
tensor_B

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [16]:
tensor_B.T

tensor([[1, 3, 5],
        [2, 4, 6]])

In [17]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 5, 11, 17],
        [11, 25, 39],
        [17, 39, 61]])

In [18]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [19]:
torch.min(x)

tensor(0)

In [20]:
torch.max(x)

tensor(90)

In [21]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [22]:
x.sum()

tensor(450)

In [23]:
x.argmin()

tensor(0)

In [24]:
x.argmax()

tensor(9)

In [25]:
x[x.argmax()]

tensor(90)

In [26]:
x.shape

torch.Size([10])

In [27]:
x_reshaped = x.reshape(5,2)
x_reshaped

tensor([[ 0, 10],
        [20, 30],
        [40, 50],
        [60, 70],
        [80, 90]])

In [28]:
x_view = x.view(2,5)
x_view

tensor([[ 0, 10, 20, 30, 40],
        [50, 60, 70, 80, 90]])

In [29]:
x_view[:,0] = 100
x_view, x

(tensor([[100,  10,  20,  30,  40],
         [100,  60,  70,  80,  90]]),
 tensor([100,  10,  20,  30,  40, 100,  60,  70,  80,  90]))

In [30]:
x_stacked = torch.stack([x,x,x],dim=1)
x_stacked,x

(tensor([[100, 100, 100],
         [ 10,  10,  10],
         [ 20,  20,  20],
         [ 30,  30,  30],
         [ 40,  40,  40],
         [100, 100, 100],
         [ 60,  60,  60],
         [ 70,  70,  70],
         [ 80,  80,  80],
         [ 90,  90,  90]]),
 tensor([100,  10,  20,  30,  40, 100,  60,  70,  80,  90]))

In [31]:
torch.hstack([x,x,x,x])

tensor([100,  10,  20,  30,  40, 100,  60,  70,  80,  90, 100,  10,  20,  30,
         40, 100,  60,  70,  80,  90, 100,  10,  20,  30,  40, 100,  60,  70,
         80,  90, 100,  10,  20,  30,  40, 100,  60,  70,  80,  90])

In [32]:
torch.squeeze(torch.tensor([[1,2,3,4],[5,6,7,8]]))

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [33]:
c = torch.zeros(1,2,3,1,2,1)
c

tensor([[[[[[0.],
            [0.]]],


          [[[0.],
            [0.]]],


          [[[0.],
            [0.]]]],



         [[[[0.],
            [0.]]],


          [[[0.],
            [0.]]],


          [[[0.],
            [0.]]]]]])

In [34]:
torch.unsqueeze(ranged,0).shape

torch.Size([1, 84])

In [35]:
x = torch.randn(2,3,5)
x

tensor([[[ 0.6624, -1.2216,  1.8483, -0.1025,  0.4287],
         [-0.8917,  1.5398,  0.6447,  0.1374, -0.9723],
         [-0.0150,  0.9729,  0.9732, -1.8062, -0.0839]],

        [[ 0.2712, -0.5296,  0.7380, -1.0539, -0.5090],
         [ 0.9251,  1.0927,  0.2463,  0.3686, -0.1731],
         [-0.8174,  0.7717,  0.3508, -1.2896,  1.8137]]])

In [36]:
torch.permute(x,(2,1,0)).shape # (5,3,2)

torch.Size([5, 3, 2])

In [56]:
tensor = torch.arange(1,10).reshape(1,3,3)
tensor, tensor.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [58]:
tensor[0][2][1]

tensor(8)

In [65]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

# Numpy to Pytorch tensor

In [67]:
import numpy as np

array = np.arange(1.0,10.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

# Random but reproducible

In [71]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3,5)

random_tensor_A, random_tensor_B

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904],
         [0.6009, 0.2566, 0.7936, 0.9408, 0.1332],
         [0.9346, 0.5936, 0.8694, 0.5677, 0.7411]]))

In [72]:
tensor.device

device(type='cpu')

In [73]:
torch.cuda.is_available()

True

In [74]:
!nvidia-smi

Thu Dec 29 12:27:07 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.60.11    Driver Version: 525.60.11    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   38C    P8     1W /  N/A |      7MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [75]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [81]:
tensor = torch.tensor([1,2,3,4])
tensor1 = torch.rand(3,4,5,6)
tensor ,tensor.device

(tensor([1, 2, 3, 4]), device(type='cpu'))

In [83]:
!nvidia-smi

Thu Dec 29 12:36:23 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.60.11    Driver Version: 525.60.11    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   41C    P8     2W /  N/A |    515MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [84]:
tensor1.device

device(type='cpu')

In [86]:
tensor_in_gpu = tensor1.to(device)
tensor_in_gpu.device

device(type='cuda', index=0)

In [87]:
!nvidia-smi

Thu Dec 29 12:40:21 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.60.11    Driver Version: 525.60.11    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   42C    P3    12W /  N/A |    515MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [88]:
# converting pytorch tensor to numpy array
numpy_tensor = tensor_in_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [93]:
tensor_back_on_to_cpu = tensor_in_gpu.cpu()
tensor_back_on_to_cpu.device

device(type='cpu')

In [1]:
!nvidia-smi

Thu May 11 11:26:30 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.41.03              Driver Version: 530.41.03    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1650         Off| 00000000:01:00.0 Off |                  N/A |
| N/A   38C    P3                5W /  N/A|      5MiB /  4096MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

# Exercises

In [96]:
# 2. Create a random tensor with shape (7, 7).
random_tensor_A = torch.rand(7,7)
random_tensor_A


tensor([[0.9112, 0.1225, 0.1341, 0.7565, 0.9348, 0.7992, 0.5783],
        [0.6648, 0.9746, 0.1774, 0.2730, 0.8497, 0.1579, 0.2243],
        [0.8650, 0.6578, 0.6615, 0.2881, 0.4931, 0.9576, 0.1999],
        [0.5039, 0.7378, 0.1548, 0.9856, 0.2502, 0.3799, 0.3647],
        [0.1742, 0.0094, 0.7819, 0.6328, 0.0317, 0.1782, 0.9942],
        [0.6911, 0.7006, 0.2009, 0.2808, 0.4245, 0.4086, 0.1574],
        [0.5412, 0.5497, 0.4367, 0.5693, 0.3018, 0.6301, 0.6886]])

In [150]:
torch.manual_seed(0)
random_tensor_A = torch.rand(7,7)
random_tensor_A

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [151]:
# torch.manual_seed(0)
random_tensor_B = torch.rand(1,7)
random_tensor_B

tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]])

In [152]:
product_mat = torch.mm(random_tensor_A, random_tensor_B.T)
product_mat

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [154]:
random_tensor_B = torch.rand(1,7)
random_tensor_B

tensor([[0.6511, 0.7745, 0.4369, 0.5191, 0.6159, 0.8102, 0.9801]])